JASYPT_ENCRYPTOR_PASS: YOUR_ENC_PASS
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    #    algorithm: PBEWithMD5AndDES
    #    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${JASYPT_ENCRYPTOR_PASS}

encpwdtest:
  test1: ENC(IfofXJ7FVaotnOu1zneOhR3jkmXAOTd6GX+6YXoXUeFFIKyhra70AjJCXoeZKePv1TJFQfjt/i5KQsLwXaZv4hgMzEc4Kqg5g3TSX/xFO1CvSND/YKQxULFo7OgHgszG)

# Using the Jasypt CLI
# java -cp jasypt-1.9.3.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="hello jasypt testing" password=YOUR_ENC_PASS algorithm=PBEWITHHMACSHA512ANDAES_256
# Programming refer to: ps/demo/jpademo/test/JasyptTest2.java
##----------------------------------------------------------------------------------##
server:
  port: 10001
  tomcat:
    connection-timeout: 5000 # unit is ms

logging:
  level:
    root: ERROR
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    ps.demo: DEBUG
  pattern:
    console: ${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr(${LOGGED_APPLICATION_NAME:-}[%15.15t]){faint} %clr(${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

spring:
  application:
    name: springboot-jpa-demo
  profiles:
    active: dev
    servlet:
      multipart:
        max-file-size: 2MB
        max-request-size: 2MB
  mvc:
    async:
      request-timeout: -1
  #      request-timeout: 300000
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolOK

    url: jdbc:h2:mem:springboot-jpa-demo;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true

  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
      trace: true
  sql:
    init:
      mode: embedded

springdoc:
  api-docs:
    path: /api-docs


management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, schema


---

spring:
  config:
    activate:
      on-profile: dev



---

spring:
  config:
    activate:
      on-profile: sit


---

spring:
  config:
    activate:
      on-profile: uat


---

spring:
  config:
    activate:
      on-profile: prod

  h2:
    console:
      path: /h2-console
      enabled: false